language: generic
sudo: required
services:
  - docker 

before_install:
  - docker build -t shubhankergoyal/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true shubhankergoyal/react-test npm test


after_success:
  - docker build -t shubhankergoyal/multi-client ./client
  - docker build -t shubhankergoyal/multi-nginx ./nginx
  - docker build -t shubhankergoyal/multi-server ./server
  - docker build -t shubhankergoyal/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shubhankergoyal/multi-client
  - docker push shubhankergoyal/multi-nginx
  - docker push shubhankergoyal/multi-server
  - docker push shubhankergoyal/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-542180042786'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
